services:
  db: 
    image: postgres:16.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: db
    networks:
      - tracker_net
    volumes: 
      - ../pgdata:/var/lib/postgresql/data
    ports: 
      - '127.0.0.1:5432:5432'
  
  api:
    build: 
      context: ../api-service
      dockerfile: ../dev-config/Dockerfile.backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports: 
      - '127.0.0.1:8080:8080'
    container_name: api
    networks:
      - tracker_net
    depends_on: 
      - db
    volumes: 
      - ../api-service:/app

  client: 
    build:
      context: ../client-service
      dockerfile: ../dev-config/Dockerfile.frontend
    ports: 
      - '127.0.0.1:3000:3000'
    container_name: client
    volumes:
      - ../client-service:/app
    networks:
      - tracker_net
    depends_on: 
      - api 
  
networks:
  tracker_net:
volumes: 
  pgdata: {}
